### ISSUE TITLE
error serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13

### ISSUE THREAD

**Issue by A-dante** [A-dante/arduino-ch340#1]
Hello i'm student of korea
I have an error in using my arduino. I want to use arduino for my project, but my one have some error. 
this is my error point:
Arduino:1.8.9 (Windows 10), Board:"Generic ESP8266 Module, 80 MHz, Flash, Disabled, All SSL ciphers (most compatible), ck, 26 MHz, 40MHz, DOUT (compatible), 512K (no SPIFFS), 2, nonos-sdk 2.2.1 (legacy), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

스케치는 프로그램 저장 공간 257696 바이트(51%)를 사용. 최대 499696 바이트.
전역 변수는 동적 메모리 26572바이트(32%)를 사용, 55348바이트의 지역변수가 남음.  최대는 81920 바이트. 
esptool.py v2.6
2.6
esptool.py v2.6
Serial port COM12
Traceback (most recent call last):
  File "C:\Users\jihun\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.5.2/tools/upload.py", line 25, in <module>
    esptool.main(fakeargs)
  File "C:/Users/jihun/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 2652, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "C:/Users/jihun/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/esptool\esptool.py", line 222, in __init__
    self._port = serial.serial_for_url(port)
  File "C:/Users/jihun/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/pyserial\serial\__init__.py", line 88, in serial_for_url
    instance.open()
  File "C:/Users/jihun/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/pyserial\serial\serialwin32.py", line 78, in open
    self._reconfigure_port()
  File "C:/Users/jihun/AppData/Local/Arduino15/packages/esp8266/hardware/esp8266/2.5.2/tools/pyserial\serial\serialwin32.py", line 222, in _reconfigure_port
    'Original message: {!r}'.format(ctypes.WinError()))
serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13, '�ý��ۿ� ������ ��ġ�� �۵����� �ʽ��ϴ�.', None, 31)
serial.serialutil.SerialException: Cannot configure port, something went wrong. Original message: PermissionError(13, '�ý��ۿ� ������ ��ġ�� �۵����� �ʽ��ϴ�.', None, 31)

I used this for the first time after buying it. At first, only time out error occurred, but after soldering it, this error occurs.
i use **ch340 usb to esp8266. PLEASE HELP**

**Comment by A-dante** [comment]
Is this device problem?
